/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shareameal;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Programa
     */
    
    private boolean isAdmin = false;
    private boolean isPerked = false;
    SpinnerNumberModel nm = new SpinnerNumberModel();
    SpinnerNumberModel nm2 = new SpinnerNumberModel();
    DefaultTableModel tablaDonar = new DefaultTableModel();
    DefaultTableModel tablaPedir = new DefaultTableModel();
    private String objetosDonables[] = {"Pan","Frutas","Verduras","Carnes","Atúnes",
   "Frijoles","Aceites","Aguas","Arroz"};
    private String objetosPedibles[] = {"Combo 1","Combo 2","Combo 3", "Combo 4"};
    ArrayList<Donante> listaDonante = new ArrayList<>();
    ArrayList<Receptor> listaPedidor = new ArrayList<>();
    
    public Programa() {
        this.setTitle("ShareAMeal - Beta V1.0");
        initComponents();
        colocarImagenes();
        configComponentesExtra();
        btn_home.setBackground(new Color(51,255,153));
        header_page_name.setText("Página principal");
    }
    
    public void getLoginUser(boolean isAdmin) {
        this.isAdmin = isAdmin;
        if(isAdmin){
            loginAsInfo.setForeground(Color.red);
            loginAsInfo.setText("Administrador");
            isPerked = true;
            
        }else{
            loginAsInfo.setForeground(Color.blue);
            loginAsInfo.setText("Invitado");
        }
    }

    private void configComponentesExtra() {
        
        //Spinner cantidad de objetos
        nm.setMaximum(20);
        nm.setMinimum(0);
        spiCantObjetos.setModel(nm);
        nm2.setMaximum(5);
        nm2.setMinimum(0);
        spiCantDonar.setModel(nm2);
        
        //Llenar tabla donador

        String[] cabeceraDonar = {"Objeto/s", "Cantidad objetos"};
        tablaDonar.setColumnIdentifiers(cabeceraDonar);
        tablaObjetos.setModel(tablaDonar);
        
        //Llenar tabla pedidor
        String[] cabeceraPedir = {"Objeto/s", "Cantidad objetos"};
        tablaPedir.setColumnIdentifiers(cabeceraPedir);
        tablaObjetosP.setModel(tablaPedir);
        
    }
    
    private void llenarLista() {
        String objetos = itemsDisponibles.getSelectedItem().toString();
        int cantidad = (int) spiCantObjetos.getValue();
        Donante donante = new Donante(cantidad, objetos);
        listaDonante.add(donante);
    }
    private void setDatos() {
        Object[] datos = new Object[tablaDonar.getColumnCount()];
        tablaDonar.setRowCount(0);
        for (Donante donante : listaDonante) {
            datos[0] = donante.getProducto();
            datos[1] = donante.getCant_producto();
            tablaDonar.addRow(datos);
        }
        tablaObjetos.setModel(tablaDonar);
    }
    
    private void llenarLista2() { 
        String objetos = comboPedir.getSelectedItem().toString();
        int cantidad = (int) spiCantDonar.getValue();
        Receptor receptor = new Receptor(objetos, cantidad);
        listaPedidor.add(receptor);
    }
    private void setDatos2() {
        Object[] datos2 = new Object[tablaPedir.getColumnCount()];
        tablaPedir.setRowCount(0);
        for (Receptor receptor : listaPedidor) {
            datos2[0] = receptor.getProductos();
            datos2[1] = receptor.getCant_productos();
            tablaPedir.addRow(datos2);
        }
        tablaObjetosP.setModel(tablaPedir);
    }
    
    
    public void colocarImagenes() {
        home_img.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/home_btn.png"));
        pedir_img.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/pedir_btn.png"));
        donar_img.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/donar_btn.png"));
        FAQ_img.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/FAQ_btn.png"));
        img_home1.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/tenedores_login.png"));
    }
    // Color de holder: 204,255,204
    // Color default: 153,255,204
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        buttons_bar = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        home_img = new javax.swing.JLabel();
        home_txt1 = new javax.swing.JLabel();
        btn_Donar = new javax.swing.JPanel();
        donar_img = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Pedir = new javax.swing.JPanel();
        pedir_img = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_FAQ = new javax.swing.JPanel();
        FAQ_img = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        header_page_name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loginAsInfo = new javax.swing.JLabel();
        header_auth_info = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        devInfoH = new javax.swing.JLabel();
        img_home1 = new javax.swing.JLabel();
        Donar = new javax.swing.JPanel();
        bgDonar = new javax.swing.JPanel();
        devInfoD = new javax.swing.JLabel();
        Donar_Title = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        itemsDisponibles = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spiCantObjetos = new javax.swing.JSpinner();
        btnSaveDonar = new javax.swing.JPanel();
        donar_btnSaveObj = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        donar_campo_dinero = new javax.swing.JTextField();
        btnSaveDonarDinero = new javax.swing.JPanel();
        donar_btnSaveDinero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaObjetos = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        btnSaveAllDonar = new javax.swing.JPanel();
        txtSaveAllDonar = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Pedir = new javax.swing.JPanel();
        bg_pedir = new javax.swing.JPanel();
        devInfoP = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        comboPedir = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        spiCantDonar = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        btnUpdatePedir = new javax.swing.JPanel();
        txtUpdatePedir = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaObjetosP = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        nombreCampo = new javax.swing.JTextField();
        btnCompletarPedido = new javax.swing.JPanel();
        txtCompletarPedido = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        direccionCampo = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        FAQ = new javax.swing.JPanel();
        devInfoFAQ = new javax.swing.JLabel();
        FAQ_Title = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(910, 510));
        bg.setPreferredSize(new java.awt.Dimension(910, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttons_bar.setBackground(new java.awt.Color(153, 255, 204));
        buttons_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(153, 255, 204));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });

        home_txt1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        home_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_txt1.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(home_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_homeLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(home_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        buttons_bar.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 100));

        btn_Donar.setBackground(new java.awt.Color(153, 255, 204));
        btn_Donar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DonarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Donar");

        javax.swing.GroupLayout btn_DonarLayout = new javax.swing.GroupLayout(btn_Donar);
        btn_Donar.setLayout(btn_DonarLayout);
        btn_DonarLayout.setHorizontalGroup(
            btn_DonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_DonarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(donar_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        btn_DonarLayout.setVerticalGroup(
            btn_DonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_DonarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(btn_DonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donar_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        buttons_bar.add(btn_Donar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 120));

        btn_Pedir.setBackground(new java.awt.Color(153, 255, 204));
        btn_Pedir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PedirMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pedir");

        javax.swing.GroupLayout btn_PedirLayout = new javax.swing.GroupLayout(btn_Pedir);
        btn_Pedir.setLayout(btn_PedirLayout);
        btn_PedirLayout.setHorizontalGroup(
            btn_PedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_PedirLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pedir_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btn_PedirLayout.setVerticalGroup(
            btn_PedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_PedirLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(btn_PedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pedir_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        buttons_bar.add(btn_Pedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 120));

        btn_FAQ.setBackground(new java.awt.Color(153, 255, 204));
        btn_FAQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FAQMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FAQ");

        javax.swing.GroupLayout btn_FAQLayout = new javax.swing.GroupLayout(btn_FAQ);
        btn_FAQ.setLayout(btn_FAQLayout);
        btn_FAQLayout.setHorizontalGroup(
            btn_FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_FAQLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(FAQ_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btn_FAQLayout.setVerticalGroup(
            btn_FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_FAQLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btn_FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FAQ_img, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        buttons_bar.add(btn_FAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 220, 100));

        header2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SHARE A MEAL");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Dashboard");

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(header2Layout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap())
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        buttons_bar.add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        bg.add(buttons_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        header.setBackground(new java.awt.Color(0, 255, 153));

        header_page_name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        header_page_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Te encuentras ahora mismo en:");

        loginAsInfo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        loginAsInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        header_auth_info.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        header_auth_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_auth_info.setText("Te has autenticado como: ");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_page_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(loginAsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(header_auth_info, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header_page_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAsInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(header_auth_info, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 810, 100));

        content.setBackground(new java.awt.Color(255, 204, 204));
        content.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SHARE A MEAL");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIO");

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("\"ShareAMeal\" es un proyecto enfocado en el ODS \"Hambre cero\"");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nuestro programa permite que las personas puedan donar alimentos, recursos a personas que lo necesiten.");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cualquier persona podrá solicitar nuestros apoyos que tenemos para ellos, estos suelen ser donados, o de nuestra parte.");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Distribuiremos los alimentos recaudados a aquellas personas que lo soliciten en nuestro programa.");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Ayudanos reportando cualquier error en el programa. Vista la zona de FAQ para más información.");

        devInfoH.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        devInfoH.setForeground(new java.awt.Color(0, 0, 0));
        devInfoH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devInfoH.setText("Beta1.0 V1 - Dev: Uriel Ramírez");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomeLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HomeLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(HomeLayout.createSequentialGroup()
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(HomeLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(devInfoH)))
                .addContainerGap())
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(img_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(img_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(devInfoH))
        );

        content.add(Home, "Home");

        Donar.setBackground(new java.awt.Color(255, 255, 255));

        bgDonar.setBackground(new java.awt.Color(255, 255, 255));

        devInfoD.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        devInfoD.setForeground(new java.awt.Color(0, 0, 0));
        devInfoD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devInfoD.setText("Beta1.0 V1 - Dev: Uriel Ramírez");

        Donar_Title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Donar_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Donar_Title.setText("Donar");

        itemsDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(objetosDonables));
        itemsDisponibles.setSelectedItem("Pan");
        itemsDisponibles.setToolTipText("Selecciona un alimento a donar");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Selecciona la cantidad");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Selecciona un alimento a donar");

        btnSaveDonar.setBackground(new java.awt.Color(102, 102, 255));
        btnSaveDonar.setToolTipText("");

        donar_btnSaveObj.setBackground(new java.awt.Color(255, 255, 255));
        donar_btnSaveObj.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        donar_btnSaveObj.setForeground(new java.awt.Color(255, 255, 255));
        donar_btnSaveObj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donar_btnSaveObj.setText("Agregar objetos");
        donar_btnSaveObj.setToolTipText("");
        donar_btnSaveObj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donar_btnSaveObjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donar_btnSaveObjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donar_btnSaveObjMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSaveDonarLayout = new javax.swing.GroupLayout(btnSaveDonar);
        btnSaveDonar.setLayout(btnSaveDonarLayout);
        btnSaveDonarLayout.setHorizontalGroup(
            btnSaveDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donar_btnSaveObj, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );
        btnSaveDonarLayout.setVerticalGroup(
            btnSaveDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donar_btnSaveObj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Donativos extras en dinero");

        donar_campo_dinero.setToolTipText("Ingresa cantidad de dinero");

        btnSaveDonarDinero.setBackground(new java.awt.Color(102, 102, 255));

        donar_btnSaveDinero.setBackground(new java.awt.Color(255, 255, 255));
        donar_btnSaveDinero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        donar_btnSaveDinero.setForeground(new java.awt.Color(255, 255, 255));
        donar_btnSaveDinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donar_btnSaveDinero.setText("Guardar cantidad");
        donar_btnSaveDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donar_btnSaveDineroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donar_btnSaveDineroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donar_btnSaveDineroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSaveDonarDineroLayout = new javax.swing.GroupLayout(btnSaveDonarDinero);
        btnSaveDonarDinero.setLayout(btnSaveDonarDineroLayout);
        btnSaveDonarDineroLayout.setHorizontalGroup(
            btnSaveDonarDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donar_btnSaveDinero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnSaveDonarDineroLayout.setVerticalGroup(
            btnSaveDonarDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donar_btnSaveDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        tablaObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaObjetos);

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Donativos guardados");

        btnSaveAllDonar.setBackground(new java.awt.Color(102, 102, 255));

        txtSaveAllDonar.setBackground(new java.awt.Color(255, 255, 255));
        txtSaveAllDonar.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtSaveAllDonar.setForeground(new java.awt.Color(255, 255, 255));
        txtSaveAllDonar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSaveAllDonar.setText("Guardar y donar");
        txtSaveAllDonar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSaveAllDonarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSaveAllDonarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSaveAllDonarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSaveAllDonarLayout = new javax.swing.GroupLayout(btnSaveAllDonar);
        btnSaveAllDonar.setLayout(btnSaveAllDonarLayout);
        btnSaveAllDonarLayout.setHorizontalGroup(
            btnSaveAllDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSaveAllDonar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnSaveAllDonarLayout.setVerticalGroup(
            btnSaveAllDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSaveAllDonar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel29.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Finalizar operacion");

        javax.swing.GroupLayout bgDonarLayout = new javax.swing.GroupLayout(bgDonar);
        bgDonar.setLayout(bgDonarLayout);
        bgDonarLayout.setHorizontalGroup(
            bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDonarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDonarLayout.createSequentialGroup()
                        .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addComponent(btnSaveDonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addComponent(spiCantObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addComponent(itemsDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(btnSaveAllDonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57))
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgDonarLayout.createSequentialGroup()
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgDonarLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgDonarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(donar_campo_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgDonarLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnSaveDonarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgDonarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addComponent(Donar_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDonarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(devInfoD)
                .addContainerGap())
        );
        bgDonarLayout.setVerticalGroup(
            bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDonarLayout.createSequentialGroup()
                .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Donar_Title)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDonarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donar_campo_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSaveDonarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(devInfoD)
                        .addGap(85, 85, 85))
                    .addGroup(bgDonarLayout.createSequentialGroup()
                        .addGroup(bgDonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgDonarLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemsDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(spiCantObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnSaveDonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveAllDonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout DonarLayout = new javax.swing.GroupLayout(Donar);
        Donar.setLayout(DonarLayout);
        DonarLayout.setHorizontalGroup(
            DonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgDonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DonarLayout.setVerticalGroup(
            DonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgDonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        content.add(Donar, "Donar");

        Pedir.setBackground(new java.awt.Color(255, 255, 255));

        bg_pedir.setBackground(new java.awt.Color(255, 255, 255));

        devInfoP.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        devInfoP.setForeground(new java.awt.Color(0, 0, 0));
        devInfoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devInfoP.setText("Beta1.0 V1 - Dev: Uriel Ramírez");

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Pedir");

        comboPedir.setModel(new javax.swing.DefaultComboBoxModel<>(objetosPedibles));
        comboPedir.setSelectedItem("Combo 1");
        comboPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPedirActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Selecciona un alimento a solicitar");

        jLabel31.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Selecciona la cantidad que deseas");

        btnUpdatePedir.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdatePedir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdatePedirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdatePedirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdatePedirMouseExited(evt);
            }
        });

        txtUpdatePedir.setBackground(new java.awt.Color(255, 255, 255));
        txtUpdatePedir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtUpdatePedir.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdatePedir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUpdatePedir.setText("Agregar alimentos");

        javax.swing.GroupLayout btnUpdatePedirLayout = new javax.swing.GroupLayout(btnUpdatePedir);
        btnUpdatePedir.setLayout(btnUpdatePedirLayout);
        btnUpdatePedirLayout.setHorizontalGroup(
            btnUpdatePedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUpdatePedir, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnUpdatePedirLayout.setVerticalGroup(
            btnUpdatePedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUpdatePedir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        tablaObjetosP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaObjetosP);

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Ingresa tu nombre");

        nombreCampo.setToolTipText("Ingresa la direccion");
        nombreCampo.setBorder(null);

        btnCompletarPedido.setBackground(new java.awt.Color(102, 102, 255));

        txtCompletarPedido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtCompletarPedido.setForeground(new java.awt.Color(255, 255, 255));
        txtCompletarPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCompletarPedido.setText("Completar pedido");
        txtCompletarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCompletarPedidoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCompletarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCompletarPedidoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCompletarPedidoLayout = new javax.swing.GroupLayout(btnCompletarPedido);
        btnCompletarPedido.setLayout(btnCompletarPedidoLayout);
        btnCompletarPedidoLayout.setHorizontalGroup(
            btnCompletarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCompletarPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnCompletarPedidoLayout.setVerticalGroup(
            btnCompletarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCompletarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jLabel34.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Ingresa tu dirección");

        direccionCampo.setToolTipText("Ingresa la direccion");
        direccionCampo.setBorder(null);

        javax.swing.GroupLayout bg_pedirLayout = new javax.swing.GroupLayout(bg_pedir);
        bg_pedir.setLayout(bg_pedirLayout);
        bg_pedirLayout.setHorizontalGroup(
            bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pedirLayout.createSequentialGroup()
                .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pedirLayout.createSequentialGroup()
                        .addContainerGap(670, Short.MAX_VALUE)
                        .addComponent(devInfoP))
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(bg_pedirLayout.createSequentialGroup()
                .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bg_pedirLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnUpdatePedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(spiCantDonar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(comboPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel34)
                                .addComponent(direccionCampo))
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pedirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompletarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        bg_pedirLayout.setVerticalGroup(
            bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pedirLayout.createSequentialGroup()
                .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(bg_pedirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(bg_pedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg_pedirLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spiCantDonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnUpdatePedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bg_pedirLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direccionCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnCompletarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bg_pedirLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(devInfoP))
        );

        javax.swing.GroupLayout PedirLayout = new javax.swing.GroupLayout(Pedir);
        Pedir.setLayout(PedirLayout);
        PedirLayout.setHorizontalGroup(
            PedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PedirLayout.setVerticalGroup(
            PedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        content.add(Pedir, "Pedir");

        FAQ.setBackground(new java.awt.Color(255, 255, 255));

        devInfoFAQ.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        devInfoFAQ.setForeground(new java.awt.Color(0, 0, 0));
        devInfoFAQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devInfoFAQ.setText("Beta1.0 V1 - Dev: Uriel Ramírez");

        FAQ_Title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        FAQ_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FAQ_Title.setText("FAQ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("¿Puedo solicitar ayudas en cualquier momento?");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("En momentos podrás escoger alimentos libremente, cuando los recursos estén por agotarse nuestro sistema");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("¿Encontraste algún error en nuestro sistema?");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Por supuesto, pero tendrán un tiempo de espera para volver a solicitar por persona");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("¿Qué alimentos puedo escoger?");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Claro que sí, podrán hacer donaciones de caridad para apoyar a nuestra caridad. Disponible en la sección de \"Donar\"");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("hará una selección automatica de paquetes de alimentos.");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("¿Puedo hacer donaciones de dinero a su proyecto?");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("No dudes en contactar al correo eléctronico de nuestros programadores");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("ramirez.salgado.angel.44@cbtis118.edu.mx");

        javax.swing.GroupLayout FAQLayout = new javax.swing.GroupLayout(FAQ);
        FAQ.setLayout(FAQLayout);
        FAQLayout.setHorizontalGroup(
            FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FAQLayout.createSequentialGroup()
                .addGroup(FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FAQLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FAQLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(devInfoFAQ))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(FAQLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(FAQ_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(FAQLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FAQLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FAQLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FAQLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        FAQLayout.setVerticalGroup(
            FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FAQLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(FAQ_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel22)
                .addGap(2, 2, 2)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(52, 52, 52)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(12, 12, 12)
                .addComponent(devInfoFAQ)
                .addContainerGap())
            .addGroup(FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FAQLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel24)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );

        content.add(FAQ, "FAQ");

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 810, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        //Seleccionado
        btn_home.setBackground(new Color(51,255,153));
        //Cambiar los demás
        btn_Donar.setBackground(new Color(153,255,204));
        btn_Pedir.setBackground(new Color(153,255,204));
        btn_FAQ.setBackground(new Color(153,255,204));
        CardLayout card = (CardLayout)content.getLayout();
        card.show(content, "Home");
        header_page_name.setText("Página principal");
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_DonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DonarMouseClicked
        //Seleccionado
        btn_Donar.setBackground(new Color(51,255,153));
        //Cambiar los demás
        btn_home.setBackground(new Color(153,255,204));
        btn_Pedir.setBackground(new Color(153,255,204));
        btn_FAQ.setBackground(new Color(153,255,204));
        CardLayout card = (CardLayout)content.getLayout();
        card.show(content, "Donar");
        header_page_name.setText("Realizar una donación");
        
    }//GEN-LAST:event_btn_DonarMouseClicked

    private void btn_PedirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PedirMouseClicked
        btn_Pedir.setBackground(new Color(51,255,153));
        
        btn_home.setBackground(new Color(153,255,204));
        btn_Donar.setBackground(new Color(153,255,204));
        btn_FAQ.setBackground(new Color(153,255,204));
        CardLayout card = (CardLayout)content.getLayout();
        card.show(content, "Pedir");
        header_page_name.setText("Solicitar recursos");
    }//GEN-LAST:event_btn_PedirMouseClicked

    private void btn_FAQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FAQMouseClicked
        btn_FAQ.setBackground(new Color(51,255,153));
        
        btn_home.setBackground(new Color(153,255,204));
        btn_Donar.setBackground(new Color(153,255,204));
        btn_Pedir.setBackground(new Color(153,255,204));
        CardLayout card = (CardLayout)content.getLayout();
        card.show(content, "FAQ");
        header_page_name.setText("Preguntas frecuentes");
    }//GEN-LAST:event_btn_FAQMouseClicked

    private void donar_btnSaveObjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donar_btnSaveObjMouseClicked
        String objetoSelect = itemsDisponibles.getSelectedItem().toString();
        int cantidadProducto = (int) spiCantObjetos.getValue();
        Donante donante = new Donante(cantidadProducto, objetoSelect);
        if(donante.getCant_producto() == 0){
            JOptionPane.showMessageDialog(getParent(), "Debes ingresar una cantidad mayor a 0", "Error en la operación", INFORMATION_MESSAGE);
        }else{
            llenarLista();
            setDatos();
            JOptionPane.showMessageDialog(getParent(), "Objetos guardados correctamente, sigue agregando más o da click en Guardar y donar", "Operación realizada con éxito", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_donar_btnSaveObjMouseClicked

    private void donar_btnSaveDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donar_btnSaveDineroMouseClicked
        if(donar_campo_dinero.getText().isEmpty()){
            JOptionPane.showMessageDialog(getParent(), "No has ingresado una cantidad", "Transacción fallida", INFORMATION_MESSAGE);
        }else{
            int cantidadDinero = Integer.parseInt(donar_campo_dinero.getText());
            Donante donante = new Donante(cantidadDinero, 0, null);
            JOptionPane.showMessageDialog(getParent(), "¡Gracias por realizar tu donativo de $" + donante.getCant_dinero() + " MXN!", "Operación realizada con éxito", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_donar_btnSaveDineroMouseClicked

    private void txtSaveAllDonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSaveAllDonarMouseClicked
        String objetoSelect = itemsDisponibles.getSelectedItem().toString();
        int cantidadProducto = (int) spiCantObjetos.getValue();
        Donante donante = new Donante(cantidadProducto, objetoSelect);
        if(tablaDonar.getRowCount() != 0){
            JOptionPane.showMessageDialog(getParent(), "Hemos recibido correctamente tu donación, ¡muchas gracias!", "Operación realizada con éxito", INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(getParent(), "No hemos recibido ningun objeto...", "Error en la operación", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtSaveAllDonarMouseClicked

    private void comboPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPedirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPedirActionPerformed
    boolean pedido = false;
    private void btnUpdatePedirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePedirMouseClicked
        String objetoSelect = comboPedir.getSelectedItem().toString();
        int cantidadProducto = (int) spiCantDonar.getValue();
        Receptor receptor = new Receptor(objetoSelect, cantidadProducto);
        btnUpdatePedir.setBackground(new Color(102,102,255));
        if(pedido == false) {
            if(cantidadProducto == 1) {
                llenarLista2();
                setDatos2();
                pedido = true;
                JOptionPane.showMessageDialog(getParent(), "Alimentos guardados correcamente", "Operación realizada con éxito", INFORMATION_MESSAGE);
            }else if(cantidadProducto >= 1){
                JOptionPane.showMessageDialog(getParent(), "Necesitas tener licencia VIP para superar el limite de pedidos", "Error en la suscripción", INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(getParent(), "Debes ingresar una cantidad mayor a 0", "Error en la operación", INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(getParent(), "Has alcanzado el limite de alimentos por el momento.", "Error en la operación", INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUpdatePedirMouseClicked

    private void txtCompletarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCompletarPedidoMouseClicked
        String objetoSelect = comboPedir.getSelectedItem().toString();
        int cantidadProducto = (int) spiCantDonar.getValue();
        Donante donante = new Donante(cantidadProducto, objetoSelect);
        btnCompletarPedido.setBackground(new Color(102,102,255));
        String comboInfo;
        String comboName = (String) comboPedir.getSelectedItem();
        if(comboPedir.getSelectedItem().equals("Combo 1")){
            comboInfo = "Pan, Carne y Frijoles";
        }else if(comboPedir.getSelectedItem().equals("Combo 2")) {
            comboInfo = "Atúnes, Frutas, Verduras";
        }else if(comboPedir.getSelectedItem().equals("Combo 3")) {
            comboInfo = "Aguas, Aceites, Pan y Arroz";
        }else if(comboPedir.getSelectedItem().equals("Combo 4")) {
            comboInfo = "Frutas, Verduras y Carnes";
        }else{
            comboInfo = "Inexistente";
        }
        if(tablaPedir.getRowCount() != 0) {
            if(!nombreCampo.getText().equals("") || !direccionCampo.getText().equals("")) {
            String nombreCliente = nombreCampo.getText();
            String direccionCliente = direccionCampo.getText();  
            JOptionPane.showMessageDialog(getParent(), "Tu pedido ha sido confirmado con los datos proporcionados\nNombre: " + nombreCliente + "\nDirección: " + direccionCliente + "\n-------------------\nInformación de tu combo: \nCombo: " + comboName + "\nContenido: " + comboInfo, "Operación realizada con éxito", INFORMATION_MESSAGE);
           }else{
                JOptionPane.showMessageDialog(getParent(), "Necesitas tener objetos en tus pedidos y/o completar los campos con tu información.", "Error en la operación", INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(getParent(), "Necesitas tener objetos en tus pedidos y/o completar los campos con tu información.", "Error en la operación", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtCompletarPedidoMouseClicked

    // Eventos visuales - Decoración de botones (Holders)
    private void donar_btnSaveObjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donar_btnSaveObjMouseEntered
        btnSaveDonar.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_donar_btnSaveObjMouseEntered
    private void donar_btnSaveObjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donar_btnSaveObjMouseExited
        btnSaveDonar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_donar_btnSaveObjMouseExited
    private void donar_btnSaveDineroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donar_btnSaveDineroMouseEntered
        btnSaveDonarDinero.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_donar_btnSaveDineroMouseEntered
    private void donar_btnSaveDineroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donar_btnSaveDineroMouseExited
        btnSaveDonarDinero.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_donar_btnSaveDineroMouseExited
    private void txtSaveAllDonarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSaveAllDonarMouseEntered
        btnSaveAllDonar.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_txtSaveAllDonarMouseEntered
    private void txtSaveAllDonarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSaveAllDonarMouseExited
        btnSaveAllDonar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_txtSaveAllDonarMouseExited
    private void txtCompletarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCompletarPedidoMouseEntered
        btnCompletarPedido.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_txtCompletarPedidoMouseEntered
    private void txtCompletarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCompletarPedidoMouseExited
        btnCompletarPedido.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_txtCompletarPedidoMouseExited
    private void btnUpdatePedirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePedirMouseEntered
       btnUpdatePedir.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_btnUpdatePedirMouseEntered
    private void btnUpdatePedirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePedirMouseExited
        btnUpdatePedir.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnUpdatePedirMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new Programa().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Donar;
    private javax.swing.JLabel Donar_Title;
    private javax.swing.JPanel FAQ;
    private javax.swing.JLabel FAQ_Title;
    private javax.swing.JLabel FAQ_img;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Pedir;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgDonar;
    private javax.swing.JPanel bg_pedir;
    private javax.swing.JPanel btnCompletarPedido;
    private javax.swing.JPanel btnSaveAllDonar;
    private javax.swing.JPanel btnSaveDonar;
    private javax.swing.JPanel btnSaveDonarDinero;
    private javax.swing.JPanel btnUpdatePedir;
    private javax.swing.JPanel btn_Donar;
    private javax.swing.JPanel btn_FAQ;
    private javax.swing.JPanel btn_Pedir;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel buttons_bar;
    private javax.swing.JComboBox<String> comboPedir;
    private javax.swing.JPanel content;
    private javax.swing.JLabel devInfoD;
    private javax.swing.JLabel devInfoFAQ;
    private javax.swing.JLabel devInfoH;
    private javax.swing.JLabel devInfoP;
    private javax.swing.JTextField direccionCampo;
    private javax.swing.JLabel donar_btnSaveDinero;
    private javax.swing.JLabel donar_btnSaveObj;
    private javax.swing.JTextField donar_campo_dinero;
    private javax.swing.JLabel donar_img;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header2;
    private javax.swing.JLabel header_auth_info;
    private javax.swing.JLabel header_page_name;
    private javax.swing.JLabel home_img;
    private javax.swing.JLabel home_txt1;
    private javax.swing.JLabel img_home1;
    private javax.swing.JComboBox<String> itemsDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel loginAsInfo;
    private javax.swing.JTextField nombreCampo;
    private javax.swing.JLabel pedir_img;
    private javax.swing.JSpinner spiCantDonar;
    private javax.swing.JSpinner spiCantObjetos;
    private javax.swing.JTable tablaObjetos;
    private javax.swing.JTable tablaObjetosP;
    private javax.swing.JLabel txtCompletarPedido;
    private javax.swing.JLabel txtSaveAllDonar;
    private javax.swing.JLabel txtUpdatePedir;
    // End of variables declaration//GEN-END:variables
}
