/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shareameal;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Alumno
 */
public class ShareAMeal extends javax.swing.JFrame {

    /**
     * Creates new form ShareAMeal
     */
    private Programa principal;
    private boolean LoggedAsAdmin = false;
    
    public ShareAMeal() {
        this.setTitle("ShareAMeal - Beta V1.0");
        initComponents();
        colocarImagenes();
    }
    
    
    private void colocarImagenes() {
        labelIconLogin.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/Logo_sm.png"));
        user_Lbl.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/usuario.png"));
        pass_Lbl.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/contraseñaLogin.png"));
        icon_loginhead.setIcon(new javax.swing.ImageIcon("src/main/java/com/images/tenedores_login.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        returnMsg = new javax.swing.JLabel();
        icon_loginhead = new javax.swing.JLabel();
        pass_Lbl = new javax.swing.JLabel();
        iniciasesion_lbl = new javax.swing.JLabel();
        user_Lbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        contraseñaLbl = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        botonEntrar = new javax.swing.JPanel();
        loginBtnTxt = new javax.swing.JLabel();
        botonInvitado = new javax.swing.JPanel();
        InvitadoBtnTxt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelIconLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        returnMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iniciasesion_lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        iniciasesion_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciasesion_lbl.setText("Iniciar sesión");

        userLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        userLbl.setText("Nombre de usuario");

        userField.setForeground(new java.awt.Color(153, 153, 153));
        userField.setText("Ingrese su nombre de usuario");
        userField.setBorder(null);
        userField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userFieldMousePressed(evt);
            }
        });

        contraseñaLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        contraseñaLbl.setText("Contraseña");

        passField.setForeground(new java.awt.Color(153, 153, 153));
        passField.setText("****************");
        passField.setBorder(null);
        passField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passFieldMousePressed(evt);
            }
        });

        botonEntrar.setBackground(new java.awt.Color(153, 255, 204));

        loginBtnTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        loginBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnTxt.setText("Entrar");
        loginBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonEntrarLayout = new javax.swing.GroupLayout(botonEntrar);
        botonEntrar.setLayout(botonEntrarLayout);
        botonEntrarLayout.setHorizontalGroup(
            botonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonEntrarLayout.setVerticalGroup(
            botonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        botonInvitado.setBackground(new java.awt.Color(153, 255, 204));
        botonInvitado.setMaximumSize(new java.awt.Dimension(46, 23));
        botonInvitado.setMinimumSize(new java.awt.Dimension(46, 23));
        botonInvitado.setPreferredSize(new java.awt.Dimension(46, 23));

        InvitadoBtnTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        InvitadoBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InvitadoBtnTxt.setText("Invitado");
        InvitadoBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvitadoBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvitadoBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvitadoBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonInvitadoLayout = new javax.swing.GroupLayout(botonInvitado);
        botonInvitado.setLayout(botonInvitadoLayout);
        botonInvitadoLayout.setHorizontalGroup(
            botonInvitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvitadoBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        botonInvitadoLayout.setVerticalGroup(
            botonInvitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvitadoBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(iniciasesion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(user_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contraseñaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(passField)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(icon_loginhead, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(iniciasesion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_loginhead, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLbl)
                    .addComponent(user_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseñaLbl)
                    .addComponent(pass_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonInvitado, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(botonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 0, 412, 500));

        jPanel4.setBackground(new java.awt.Color(0, 255, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(labelIconLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(labelIconLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseClicked
        //Comprobacion: Si los campos NO son vacios     
        if(!userField.getText().equals("Ingrese su nombre de usuario") && !userField.getText().equals("")){
                //Comprobacion para login como ADMIN
                 if(userField.getText().equals("admin") && String.valueOf(passField.getPassword()).equals("admin")){
                    principal = new Programa();
                    LoggedAsAdmin = true;
                    principal.getLoginUser(LoggedAsAdmin);
                    principal.setVisible(true);
                    this.setVisible(false);
                 //Comprobacion para login como USUARIO   
                 }else if(userField.getText().equals("usuario") && String.valueOf(passField.getPassword()).equals("123456")){    
                    principal = new Programa();
                    LoggedAsAdmin = false;
                    principal.getLoginUser(LoggedAsAdmin);
                    principal.setVisible(true);
                    this.setVisible(false);
                 //Si no se cumple ningun caso, mensaje de error
                 }else{
                     returnMsg.setForeground(Color.red);
                     returnMsg.setText("El usuario o contraseña son incorrectos, verifica los datos.");
                 }
        //Comprobacion si los campos son vacios, mensaje de error.
        }else{
            returnMsg.setForeground(Color.red);
            returnMsg.setText("Necesitas llenar todos los campos de autenticacion");
        }
    }//GEN-LAST:event_loginBtnTxtMouseClicked

    private void userFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userFieldMousePressed
        if(userField.getText().equals("Ingrese su nombre de usuario")) {
            userField.setText("");
            userField.setForeground(Color.black);
            returnMsg.setText("");
        }
        if(String.valueOf(passField.getPassword()).isEmpty()) {
            passField.setText("****************");
            passField.setForeground(Color.gray);
            returnMsg.setText("");
        }
    }//GEN-LAST:event_userFieldMousePressed

    private void passFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passFieldMousePressed
        if (String.valueOf(passField.getPassword()).equals("****************")) {
            passField.setText("");
            passField.setForeground(Color.black);
            returnMsg.setText("");
        }
        if(userField.getText().isEmpty()) {
            userField.setText("Ingrese su nombre de usuario");
            userField.setForeground(Color.gray);
            returnMsg.setText("");
        }
    }//GEN-LAST:event_passFieldMousePressed

    private void loginBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseEntered
        botonEntrar.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_loginBtnTxtMouseEntered

    private void loginBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseExited
        botonEntrar.setBackground(new Color(153, 255, 204));
    }//GEN-LAST:event_loginBtnTxtMouseExited

    private void InvitadoBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvitadoBtnTxtMouseEntered
        botonInvitado.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_InvitadoBtnTxtMouseEntered

    private void InvitadoBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvitadoBtnTxtMouseExited
        botonInvitado.setBackground(new Color(153, 255, 204));
    }//GEN-LAST:event_InvitadoBtnTxtMouseExited

    private void InvitadoBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvitadoBtnTxtMouseClicked
        principal = new Programa();
        LoggedAsAdmin = false;
        principal.getLoginUser(LoggedAsAdmin);
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InvitadoBtnTxtMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareAMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareAMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareAMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareAMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShareAMeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InvitadoBtnTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel botonEntrar;
    private javax.swing.JPanel botonInvitado;
    private javax.swing.JLabel contraseñaLbl;
    private javax.swing.JLabel icon_loginhead;
    private javax.swing.JLabel iniciasesion_lbl;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelIconLogin;
    private javax.swing.JLabel loginBtnTxt;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel pass_Lbl;
    private javax.swing.JLabel returnMsg;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLbl;
    private javax.swing.JLabel user_Lbl;
    // End of variables declaration//GEN-END:variables
}
